name: Cypress Github Action
on: push
jobs:
  basic-pnpm:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@9
      - name: Install dependencies
        run: pnpm i
      - name: Start dev server
        run: pnpm dev
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: /home/runner/work/dfweb-v4/dfweb-v4